enum componentTypes {
  PLAYER_MOVABLE = 'PLAYER_MOVABLE',
  GRAPHICS = 'GRAPHICS',
  SPRITE = 'SPRITE',
  FOOD_TIMER = 'FOOD_TIMER',
  EATABLE = 'EATABLE',
  SCORE = 'SCORE',
  TEXT = 'TEXT',
  GAME_RUNNING = 'GAME_RUNNING',
  SPEED = 'SPEED',
  DIRECTION = 'DIRECTION'
}

export default componentTypes;
